# Install script for directory: M:/gafferDependencies/cortex-9.21.1/src/IECorePython

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "M:/gaffer")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/Debug/IECorePython.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/Release/IECorePython.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/MinSizeRel/IECorePython.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/RelWithDebInfo/IECorePython.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/Debug/IECorePython.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/Release/IECorePython.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/MinSizeRel/IECorePython.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "M:/gafferDependencies/cortex-9.21.1/gafferBuild/src/IECorePython/RelWithDebInfo/IECorePython.dll")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/IECorePython" TYPE FILE FILES
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/AddSmoothSkinningInfluencesOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/AlexaLogcToLinearOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/AngleConversionBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/AttributeStateBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/BezierAlgoBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/BinaryFrameListBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/BlindDataHolderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/BoundedKDTreeBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CINImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CINImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CachedReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CamelCaseBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CameraBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CameraControllerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CapturingRendererBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ChannelOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CineonToLinearOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ClampOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ClientDisplayDriverBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ClippingPlaneBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ColorSpaceTransformOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ColorTransformOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CompoundDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CompoundFrameListBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CompoundObjectBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CompoundParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CompressSmoothSkinningDataOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ContrastSmoothSkinningWeightsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ConverterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CoordinateSystemBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CubeColorLookupBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CubeColorLookupDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CubeColorLookupParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CubeColorTransformOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CubicBasisBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurveExtrudeOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurveLineariserBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurveTangentsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurveTracerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurvesAlgoBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurvesMergeOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurvesPrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/CurvesPrimitiveEvaluatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DPXImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DPXImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DataAlgoBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DataCastOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DataConvertOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DataInterleaveOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DataPromoteOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DateTimeDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DateTimeParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DecompressSmoothSkinningDataOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DeepImageConverterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DeepImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DeepImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DeepPixelBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DirNameParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DiskPrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DisplayBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DisplayDriverBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/DisplayDriverServerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/EXRDeepImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/EXRDeepImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/EXRImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/EXRImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/EmptyFrameListBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/EnvMapSamplerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ExceptionBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ExclusionFrameListBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/Export.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ExternalProceduralBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FaceAreaOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FaceVaryingPromotionOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FileNameParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FileSequenceBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FileSequenceFunctionsBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FileSequenceParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FileSequenceVectorParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FontBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FrameListBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FrameListParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FrameRangeBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/FromCoreConverterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/GeometricTypedDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/GradeBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/GroupBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/HalfBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/HdrMergeOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/HeaderGeneratorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/HenyeyGreensteinBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/HexConversionBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/IECoreBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageCompositeOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageCropOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageDiffOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageDisplayDriverBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImagePremultiplyOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImagePrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImagePrimitiveEvaluatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageThinnerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageUnpremultiplyOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathBoxBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathBoxVectorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathColorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathColorVectorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathEulerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathMatrixBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathMatrixVectorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathPlaneBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathQuatBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathQuatVectorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathRandomBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathRootsBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathVecBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImathVecVectorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImfBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ImfTimeCodeBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/IndexedIOBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/InternedStringBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/InverseDistanceWeightedInterpolationBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/JPEGImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/JPEGImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/KDTreeBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LRUCacheBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LensDistortOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LensModelBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LevenbergMarquardtBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LightBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LimitSmoothSkinningInfluencesOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LineSegmentBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LinearToAlexaLogcOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LinearToCineonOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LinearToPanalogOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LinearToRec709OpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LinearToSRGBOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LinkedSceneBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LookupBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/LuminanceOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MPlayDisplayDriverBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MathBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MatrixMotionTransformBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MatrixMultiplyOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MatrixTransformBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MedianCutSamplerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshAlgoBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshDistortionsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshFaceFilterOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshMergeOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshNormalsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshPrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshPrimitiveBuilderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshPrimitiveEvaluatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshPrimitiveShrinkWrapOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshTangentsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MeshVertexReorderOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MessageHandlerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MixSmoothSkinningWeightsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ModifyOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MotionPrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/MurmurHashBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/NParticleReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/NURBSPrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/NormalizeSmoothSkinningWeightsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/NullObjectBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/NumericParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/OBJReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ObjectBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ObjectInterpolatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ObjectParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ObjectPoolBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ObjectReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ObjectVectorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ObjectWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/OpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/OptionsBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/OversamplesCalculatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PDCParticleReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PDCParticleWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PNGImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PanalogToLinearOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ParameterisedBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ParameterisedProceduralBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ParticleReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ParticleWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PatchMeshPrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PathParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PathVectorParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PerlinNoiseBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointBoundsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointDensitiesOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointDistributionBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointDistributionOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointNormalsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointRepulsionOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointSmoothSkinningOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointVelocityDisplaceOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointerFromSWIG.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointsAlgoBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointsMotionOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointsPrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointsPrimitiveEvaluatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PolygonAlgoBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PreWorldRenderableBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PrimitiveEvaluatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PrimitiveOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PrimitiveVariableBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RadixSortBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RandomRotationOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/Rec709ToLinearOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RefCountedBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RemoveSmoothSkinningInfluencesOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RenderableBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RendererBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ReorderSmoothSkinningInfluencesOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ReorderedFrameListBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ReversedFrameListBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RunTimeTypedBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SGIImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SRGBToLinearOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SampledSceneInterfaceBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SceneCacheBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SceneInterfaceBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ScopedGILLock.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ScopedGILRelease.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SearchPathBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ShaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SharedSceneInterfacesBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SimpleTypedDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SimpleTypedParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SmoothSkinningDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SmoothSmoothSkinningWeightsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SpherePrimitiveBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SpherePrimitiveEvaluatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SplineBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SplineDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SplineParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SplineToImageBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/StandardRadialLensModelBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/StateRenderableBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SummedAreaOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TGAImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TGAImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TIFFImageReaderBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TIFFImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimeCodeDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimeCodeParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimeDurationDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimeDurationParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimePeriodBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimePeriodDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimePeriodParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TimerBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ToCoreConverterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TransferSmoothSkinningWeightsOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TransformBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TransformOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TransformationMatrixBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TransformationMatrixDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TriangleAlgoBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TriangulateOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TriangulatorBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TurbulenceBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TypeIdBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TypedObjectParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TypedParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TypedPrimitiveOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TypedPrimitiveParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/UVDistortOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/UnicodeToStringBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ValidatedStringParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/VectorDataFilterOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/VectorTypedDataBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/VectorTypedParameterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/VisibleRenderableBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/WarpOpBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/WrapperGarbageCollector.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/WriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/YUVImageWriterBinding.h"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/GeometricTypedDataBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ParameterBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/PointerFromSWIG.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/ReaderBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RefCountedBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/RunTimeTypedBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/SimpleTypedDataBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TypedObjectParameterBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/TypedParameterBinding.inl"
    "M:/gafferDependencies/cortex-9.21.1/src/IECorePython/../../include/IECorePython/VectorTypedDataBinding.inl"
    )
endif()

