cd %~dp0%..\\appleseed-1.6.0-beta

mkdir sandbox\bin
mkdir sandbox\schemas

mkdir build
cd build
rm -f CMakeCache.txt

cmake -Wno-dev -G %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=Release -DWITH_CLI=ON -DWITH_STUDIO=OFF -DWITH_TOOLS=OFF -DWITH_PYTHON=ON -DWITH_OSL=ON -DUSE_STATIC_BOOST=OFF -DUSE_STATIC_OIIO=OFF -DUSE_STATIC_OSL=ON -DUSE_EXTERNAL_ZLIB=ON -DUSE_EXTERNAL_EXR=ON -DUSE_EXTERNAL_PNG=ON -DUSE_EXTERNAL_XERCES=ON -DUSE_EXTERNAL_OSL=ON -DUSE_EXTERNAL_OIIO=ON -DUSE_EXTERNAL_ALEMBIC=ON -DWARNINGS_AS_ERRORS=OFF -DCMAKE_PREFIX_PATH=%BUILD_DIR% -DCMAKE_INSTALL_PREFIX=%BUILD_DIR%\appleseed -DBOOST_ROOT=%BUILD_DIR% ..
cmake --build . --config Release --target install

cd %ROOT_DIR%
